version: '2'

services:

    spring:
        image: rranjos/auth-jwt:v1
        depends_on:
        - minio
        ports:
            - "8080:8080"
   
    minio:
        image: minio/minio
        ports:
          - '9000:9000'
          - '9001:9001' 
        environment:
          - MINIO_ROOT_USER=uYiuxSF6h5VNmE5J
          - MINIO_ROOT_PASSWORD=bSHLMDXT4npWZ5WJxmBqI1OGBnBWZryS
          - "MINIO_ACCESS_KEY=uYiuxSF6h5VNmE5J"
          - "MINIO_SECRET_KEY=bSHLMDXT4npWZ5WJxmBqI1OGBnBWZryS"
          - MINIO_SKIP_CLIENT=yes
        command: server /data --console-address ":9001"
        
    app:
        image: rranjos/dxnet-app:v1
        ports:
            - "4200:80"

    createbuckets:
        image: minio/mc
        depends_on:
          - minio
        entrypoint: >
          /bin/sh -c "
          /usr/bin/mc config host add myminio http://minio:9000 uYiuxSF6h5VNmE5J bSHLMDXT4npWZ5WJxmBqI1OGBnBWZryS;
          /usr/bin/mc rm -r --force myminio/images;
          /usr/bin/mc mb myminio/images;
          /usr/bin/mc anonymous set public myminio/images;
          exit 0;
          "